// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Xausdorf/qr-pay-hub/internal/domain/repository (interfaces: UnitOfWork,AccountRepository,TransactionRepository,IdempotencyRepository)

package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/Xausdorf/qr-pay-hub/internal/domain/entity"
	repository "github.com/Xausdorf/qr-pay-hub/internal/domain/repository"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

type MockUnitOfWork struct {
	ctrl     *gomock.Controller
	recorder *MockUnitOfWorkMockRecorder
}

type MockUnitOfWorkMockRecorder struct {
	mock *MockUnitOfWork
}

func NewMockUnitOfWork(ctrl *gomock.Controller) *MockUnitOfWork {
	mock := &MockUnitOfWork{ctrl: ctrl}
	mock.recorder = &MockUnitOfWorkMockRecorder{mock}
	return mock
}

func (m *MockUnitOfWork) EXPECT() *MockUnitOfWorkMockRecorder {
	return m.recorder
}

func (m *MockUnitOfWork) Begin(ctx context.Context) (repository.UnitOfWork, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", ctx)
	ret0, _ := ret[0].(repository.UnitOfWork)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockUnitOfWorkMockRecorder) Begin(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockUnitOfWork)(nil).Begin), ctx)
}

func (m *MockUnitOfWork) Commit(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockUnitOfWorkMockRecorder) Commit(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockUnitOfWork)(nil).Commit), ctx)
}

func (m *MockUnitOfWork) Rollback(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockUnitOfWorkMockRecorder) Rollback(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockUnitOfWork)(nil).Rollback), ctx)
}

func (m *MockUnitOfWork) Accounts() repository.AccountRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Accounts")
	ret0, _ := ret[0].(repository.AccountRepository)
	return ret0
}

func (mr *MockUnitOfWorkMockRecorder) Accounts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Accounts", reflect.TypeOf((*MockUnitOfWork)(nil).Accounts))
}

func (m *MockUnitOfWork) Transactions() repository.TransactionRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transactions")
	ret0, _ := ret[0].(repository.TransactionRepository)
	return ret0
}

func (mr *MockUnitOfWorkMockRecorder) Transactions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transactions", reflect.TypeOf((*MockUnitOfWork)(nil).Transactions))
}

func (m *MockUnitOfWork) Idempotency() repository.IdempotencyRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Idempotency")
	ret0, _ := ret[0].(repository.IdempotencyRepository)
	return ret0
}

func (mr *MockUnitOfWorkMockRecorder) Idempotency() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Idempotency", reflect.TypeOf((*MockUnitOfWork)(nil).Idempotency))
}

type MockAccountRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAccountRepositoryMockRecorder
}

type MockAccountRepositoryMockRecorder struct {
	mock *MockAccountRepository
}

func NewMockAccountRepository(ctrl *gomock.Controller) *MockAccountRepository {
	mock := &MockAccountRepository{ctrl: ctrl}
	mock.recorder = &MockAccountRepositoryMockRecorder{mock}
	return mock
}

func (m *MockAccountRepository) EXPECT() *MockAccountRepositoryMockRecorder {
	return m.recorder
}

func (m *MockAccountRepository) FindByIDForUpdate(ctx context.Context, id uuid.UUID) (*entity.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIDForUpdate", ctx, id)
	ret0, _ := ret[0].(*entity.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockAccountRepositoryMockRecorder) FindByIDForUpdate(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIDForUpdate", reflect.TypeOf((*MockAccountRepository)(nil).FindByIDForUpdate), ctx, id)
}

func (m *MockAccountRepository) UpdateBalance(ctx context.Context, id uuid.UUID, newBalance int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBalance", ctx, id, newBalance)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockAccountRepositoryMockRecorder) UpdateBalance(ctx, id, newBalance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBalance", reflect.TypeOf((*MockAccountRepository)(nil).UpdateBalance), ctx, id, newBalance)
}

type MockTransactionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionRepositoryMockRecorder
}

type MockTransactionRepositoryMockRecorder struct {
	mock *MockTransactionRepository
}

func NewMockTransactionRepository(ctrl *gomock.Controller) *MockTransactionRepository {
	mock := &MockTransactionRepository{ctrl: ctrl}
	mock.recorder = &MockTransactionRepositoryMockRecorder{mock}
	return mock
}

func (m *MockTransactionRepository) EXPECT() *MockTransactionRepositoryMockRecorder {
	return m.recorder
}

func (m *MockTransactionRepository) Create(ctx context.Context, tx *entity.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockTransactionRepositoryMockRecorder) Create(ctx, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTransactionRepository)(nil).Create), ctx, tx)
}

type MockIdempotencyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIdempotencyRepositoryMockRecorder
}

type MockIdempotencyRepositoryMockRecorder struct {
	mock *MockIdempotencyRepository
}

func NewMockIdempotencyRepository(ctrl *gomock.Controller) *MockIdempotencyRepository {
	mock := &MockIdempotencyRepository{ctrl: ctrl}
	mock.recorder = &MockIdempotencyRepositoryMockRecorder{mock}
	return mock
}

func (m *MockIdempotencyRepository) EXPECT() *MockIdempotencyRepositoryMockRecorder {
	return m.recorder
}

func (m *MockIdempotencyRepository) Find(ctx context.Context, key string) (*entity.IdempotencyRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, key)
	ret0, _ := ret[0].(*entity.IdempotencyRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockIdempotencyRepositoryMockRecorder) Find(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockIdempotencyRepository)(nil).Find), ctx, key)
}

func (m *MockIdempotencyRepository) Save(ctx context.Context, record *entity.IdempotencyRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockIdempotencyRepositoryMockRecorder) Save(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIdempotencyRepository)(nil).Save), ctx, record)
}

func (m *MockIdempotencyRepository) Lock(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lock", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockIdempotencyRepositoryMockRecorder) Lock(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lock", reflect.TypeOf((*MockIdempotencyRepository)(nil).Lock), ctx, key)
}

var _ = time.Now
